### ISSUE TITLE
Change memory monitor default to false

### ISSUE THREAD

**Issue by jfberry** [UnownHash/Rotom#35]
Default.json should have memory monitor as false; this monitoring causes confusion in many cases and should likely be 'opt in'

**Comment by esauvisky** [comment]
I agree 100%.

Mobile operating systems are designed to make efficient use of available memory. They tend to keep the RAM as full as possible for the sake of performance. Besides, the concept of "start memory" (memStart) is also misleading, as the memory management in mobile devices is dynamic, and there's no such thing as a "fixed initial amount of memory" that an app has after launching it.

The criterias for when to trigger the restart/reboots are also based on arbitrary thresholds and ratios. Different hardwares allocate RSS ammounts according to several variables, meaning this would require different parameters for each, so it's not even an universally applicable solution for all use cases.

I think this feature focuses too much on treating the symptoms of an issue rather than identifying and addressing the underlying causes (such as memory leaks or inneficcient memory usage).

**Comment by jfberry** [comment]
This was a sticking-plaster solution which was based around the prevalent mitm architecture and recognition that the third party libraries connected to in the mitm leak over time.  There are other architectural solutions which can solve the issue but I am not aware of these being used in any public MITM.
But regardless, without tuning to your individual situations the monitoring causes restarts/reboots in an unexpected way and should start off, and any PR to change the default will be approved.

**Comment by jfberry** [comment]
Resolved in #39
